# Generated by Django 5.2.8 on 2025-11-24 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employers/profile_pictures/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('basic_info_completed', models.BooleanField(default=False)),
                ('company_info_completed', models.BooleanField(default=False)),
                ('is_profile_public', models.BooleanField(default=True)),
                ('total_jobs_posted', models.PositiveIntegerField(default=0)),
                ('total_projects_posted', models.PositiveIntegerField(default=0)),
                ('total_applications_received', models.PositiveIntegerField(default=0)),
                ('total_hires', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='EmployerCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companySize', models.PositiveIntegerField(blank=True, null=True)),
                ('isFederalContractor', models.BooleanField(default=False)),
                ('primaryState', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalStates', models.JSONField(default=list)),
                ('eeoStatement', models.TextField(blank=True, null=True)),
                ('autoScanEnabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Employer Compliance',
                'verbose_name_plural': 'Employer Compliance Records',
                'db_table': 'employer_compliance',
            },
        ),
        migrations.CreateModel(
            name='EmployerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('auto_matching', models.BooleanField(default=True)),
                ('skill_match_threshold', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_required', models.BooleanField(default=True)),
                ('location_preference', models.CharField(choices=[('any', 'Any'), ('local', 'Local'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='any', max_length=20)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Employer Preference',
                'verbose_name_plural': 'Employer Preferences',
                'db_table': 'employer_preferences',
            },
        ),
        migrations.CreateModel(
            name='CandidateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('pass', 'Pass'), ('reject', 'Reject')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_actions', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Candidate Action',
                'verbose_name_plural': 'Candidate Actions',
                'db_table': 'candidate_actions',
                'ordering': ['-created_at'],
                'unique_together': {('employer', 'candidate_id')},
            },
        ),
    ]
