# Generated by Django 5.2.6 on 2025-10-03 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_name_company_company_name'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='logoImage',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='size',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='values',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='companies.company'),
        ),
    ]
