# Generated by Django 5.2.6 on 2025-11-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_remove_employer_companyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('pass', 'Pass'), ('reject', 'Reject')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_actions', to='employers.employer')),
            ],
            options={
                'verbose_name': 'Candidate Action',
                'verbose_name_plural': 'Candidate Actions',
                'db_table': 'candidate_actions',
                'ordering': ['-created_at'],
                'unique_together': {('employer', 'candidate_id')},
            },
        ),
    ]
