# Generated by Django 5.2.8 on 2026-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_alter_employer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaction',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
