# Generated by Django 5.2.8 on 2026-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_candidateaction_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='banner_seen',
            field=models.BooleanField(default=False),
        ),
    ]
