# Generated by Django 5.2.8 on 2026-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employer_banner_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='banner_seen',
            field=models.BooleanField(default=True),
        ),
    ]
