# Generated by Django 5.2.6 on 2025-11-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeetMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=255)),
                ('meeting_url', models.URLField()),
                ('conference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_meet', to='applications.interview')),
            ],
            options={
                'verbose_name': 'Google Meet Meeting',
                'verbose_name_plural': 'Google Meet Meetings',
                'db_table': 'google_meet_meetings',
                'ordering': ['-created_at'],
            },
        ),
    ]
