# Generated by Django 5.2.6 on 2025-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewrequest',
            old_name='zoomLink',
            new_name='meetLink',
        ),
    ]
