# Generated by Django 5.2.6 on 2025-11-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_googlemeetmeeting'),
        ('applications', '0002_rename_zoomlink_interviewrequest_meetlink'),
    ]

    operations = [
    ]
