# Generated by Django 5.2.8 on 2026-04-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_interviewrequest_is_read_jobapplication_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_read_by_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_read_by_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='is_read_by_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='is_read_by_employer',
            field=models.BooleanField(default=False),
        ),
    ]
