# Generated by Django 5.2.8 on 2025-11-24 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('workStyle', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('in-person', 'In-Person')], default='remote', max_length=20)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('wriing', 'Writing'), ('technology/Digital', 'Technology/Digital'), ('creative/,media', 'Creative/Media'), ('business/finance', 'Business/Finance'), ('trades/labour', 'Trades/Labour'), ('healthcare & welness', 'Healthcare & Wellness'), ('education & training', 'Education & Training'), ('hospitality & services', 'Hospitality & Services'), ('nonprofit/community work', 'Nonprofit/Community Work'), ('other', 'Other')], max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('experienceLevel', models.CharField(choices=[('entry', 'Entry'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive'), ('junior', 'Junior')], max_length=20)),
                ('employmentType', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20)),
                ('hasTemporaryOption', models.BooleanField(default=False)),
                ('temporaryDuration', models.CharField(blank=True, max_length=100, null=True)),
                ('salaryRangeMin', models.PositiveIntegerField(blank=True, null=True)),
                ('salaryRangeMax', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('is_salary_negotiable', models.BooleanField(default=True)),
                ('benefits', models.JSONField(default=list)),
                ('applicationDeadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('filled', 'Filled')], default='draft', max_length=20)),
                ('skill_match_threshold', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_weight', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('education_weight', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('location_weight', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tags', models.JSONField(default=list)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('hired_count', models.PositiveIntegerField(default=0)),
                ('job_tags', models.JSONField(blank=True, default=list, null=True)),
                ('job_profile_summary', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native')], default='conversational', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_languages', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Language',
                'verbose_name_plural': 'Job Languages',
                'db_table': 'job_languages',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'db_table': 'job_skills',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='jobs_status_24a2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joblanguage',
            unique_together={('job', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'name')},
        ),
    ]
