# Generated by Django 5.2.6 on 2025-10-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_locatio_842270_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_weight',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_weight',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_salary_negotiable',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location_weight',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_period',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_match_threshold',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='temporaryDuration',
        ),
    ]
