# Generated by Django 5.2.6 on 2025-10-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_jobs_locatio_842270_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
