# Generated by Django 5.2.8 on 2025-12-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='query',
            new_name='search_query',
        ),
    ]
