# Generated by Django 5.2.6 on 2025-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_education_weight_job_experience_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
