# Generated by Django 5.2.8 on 2025-12-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_query_job_search_query'),
    ]

    operations = [
    ]
