# Generated by Django 5.2.6 on 2025-10-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_slug"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="jobs_company_0582d9_idx",
        ),
    ]
