# Generated by Django 5.2.6 on 2025-12-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_fix_query_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Check if the column 'query' exists and 'search_query' doesn't exist
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name='jobs' AND column_name='query')
                AND NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='jobs' AND column_name='search_query') THEN
                    -- Rename the column
                    ALTER TABLE jobs RENAME COLUMN query TO search_query;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                -- Check if the column 'search_query' exists and 'query' doesn't exist
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name='jobs' AND column_name='search_query')
                AND NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name='jobs' AND column_name='query') THEN
                    -- Rename the column back
                    ALTER TABLE jobs RENAME COLUMN search_query TO query;
                END IF;
            END $$;
            """
        ),
    ]
