# Generated by Django 5.2.6 on 2025-10-10 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_merge_20251009_1219"),
        ("jobs", "0006_remove_job_jobs_company_0582d9_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["company", "status"], name="jobs_company_0582d9_idx"
            ),
        ),
    ]
