# Generated by Django 5.2.6 on 2025-10-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobView",
        ),
    ]
