# Generated by Django 5.2.6 on 2025-11-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_delete_jobview'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_index_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_tags',
            field=models.JSONField(default=list),
        ),
    ]
