# Generated by Django 5.2.8 on 2026-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('in-progress', 'In Progress'), ('filled', 'Filled'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
