# Generated by Django 5.2.8 on 2026-01-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
