# Generated by Django 5.2.6 on 2025-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_job_index_id_job_job_profile_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
