# Generated by Django 5.2.8 on 2026-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_professional_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('business_office', 'Business & Office'), ('finance_accounting', 'Finance & Accounting'), ('marketing_sales_communication', 'Marketing, Sales & Communication'), ('technology', 'Technology'), ('education_training', 'Education and Training'), ('healthcare_wellness', 'Healthcare & Wellness'), ('skilled_trades_labor', 'Skilled Trades & Labor'), ('transportation_logistics', 'Transportation & Logistics'), ('creative_design', 'Creative & Design'), ('legal_government', 'Legal & Government'), ('science_engineering_research', 'Science, Engineering & Research'), ('hospitality_service', 'Hospitality & Service'), ('retail_consumer_services', 'Retail & Consumer Services'), ('nonprofit_social_impact', 'Nonprofit & Social Impact'), ('other', 'Other')], max_length=100),
        ),
    ]
