# Generated by Django 5.2.6 on 2025-11-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experienceLevel',
            field=models.CharField(choices=[('entry', 'Entry'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive'), ('junior', 'Junior')], max_length=20),
        ),
    ]
