# Generated by Django 5.2.8 on 2026-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_salary_currency'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE jobs ALTER COLUMN search_query TYPE jsonb USING CASE WHEN search_query IS NOT NULL AND search_query != \'\' THEN jsonb_build_array(search_query) ELSE \'[]\'::jsonb END',
            reverse_sql='ALTER TABLE jobs ALTER COLUMN search_query TYPE text USING search_query->>0',
        ),
        migrations.AlterField(
            model_name='job',
            name='search_query',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
