# Generated by Django 5.2.8 on 2025-11-24 05:49

import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=2000)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('writing', 'Writing'), ('technology/Digital', 'Technology/Digital'), ('creative/,media', 'Creative/Media'), ('business/finance', 'Business/Finance'), ('trades/labour', 'Trades/Labour'), ('healthcare & welness', 'Healthcare & Wellness'), ('education & training', 'Education & Training'), ('hospitality & services', 'Hospitality & Services'), ('nonprofit/community work', 'Nonprofit/Community Work'), ('other', 'Other')], max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('paymentType', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], max_length=20)),
                ('paymentAmount', models.PositiveIntegerField()),
                ('estimatedHours', models.CharField(max_length=100)),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex'), ('expert', 'Expert')], default='moderate', max_length=20)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_currency', models.CharField(default='USD', max_length=3)),
                ('is_budget_negotiable', models.BooleanField(default=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(default=projects.models.get_default_deadline)),
                ('is_timeline_flexible', models.BooleanField(default=False)),
                ('experience_min_years', models.PositiveIntegerField(default=0)),
                ('experience_max_years', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('high-school', 'High School'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('none', 'None')], default='bachelor', max_length=20)),
                ('education_fields', models.JSONField(default=list)),
                ('deliverables', models.JSONField(default=list)),
                ('tools', models.JSONField(default=list)),
                ('technologies', models.JSONField(default=list)),
                ('work_style', models.CharField(choices=[('remote', 'Remote'), ('office', 'Office'), ('hybrid', 'Hybrid')], default='remote', max_length=20)),
                ('collaboration', models.CharField(choices=[('independent', 'Independent'), ('team', 'Team'), ('client-involved', 'Client Involved')], default='independent', max_length=20)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_applicants', models.PositiveIntegerField(default=50)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('skill_match_threshold', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_weight', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('education_weight', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('portfolio_weight', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tags', models.JSONField(default=list)),
                ('project_tags', models.JSONField(blank=True, default=list, null=True)),
                ('project_profile_summary', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('hired_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('due_date', models.DateField()),
                ('payment_amount', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'db_table': 'project_milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Skill',
                'verbose_name_plural': 'Project Skills',
                'db_table': 'project_skills',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'created_at'], name='projects_status_35a638_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='projects_company_c1ab17_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'complexity'], name='projects_categor_f518af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectskill',
            unique_together={('project', 'name')},
        ),
    ]
