# Generated by Django 5.2.6 on 2025-10-07 07:17

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=projects.models.get_default_deadline),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
