# Generated by Django 5.2.6 on 2025-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_deadline_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
