# Generated by Django 5.2.8 on 2026-01-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_fix_project_query_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='work_style',
            field=models.CharField(choices=[('remote', 'Remote'), ('in-person', 'In-Person'), ('hybrid', 'Hybrid')], default='remote', max_length=20),
        ),
    ]
