# Generated by Django 5.2.6 on 2025-10-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectView",
        ),
    ]
