# Generated by Django 5.2.8 on 2026-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_professional_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasTemporaryOption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='temporaryDuration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
