# Generated by Django 5.2.6 on 2025-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_delete_projectview'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_index_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.JSONField(default=list),
        ),
    ]
