# Generated by Django 5.2.6 on 2025-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_project_index_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
