# Generated by Django 5.2.8 on 2026-02-17 06:57

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_hastemporaryoption_project_temporaryduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_timezone',
            field=timezone_field.fields.TimeZoneField(default='America/New_York', help_text='Timezone for this project posting'),
        ),
    ]
