# Generated by Django 5.2.6 on 2025-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('writing', 'Writing'), ('technology/Digital', 'Technology/Digital'), ('creative/,media', 'Creative/Media'), ('business/finance', 'Business/Finance'), ('trades/labour', 'Trades/Labour'), ('healthcare & welness', 'Healthcare & Wellness'), ('education & training', 'Education & Training'), ('hospitality & services', 'Hospitality & Services'), ('nonprofit/community work', 'Nonprofit/Community Work'), ('other', 'Other')], max_length=100),
        ),
    ]
