# Generated by Django 5.2.6 on 2025-11-18 13:07

import django.core.validators
import django.db.models.deletion
import vr_meet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('interview', 'Interview'), ('networking', 'Networking'), ('casual', 'Casual')], default='interview', max_length=30)),
                ('environment', models.CharField(choices=[('office', 'Office'), ('cafe', 'Cafe'), ('natural', 'Natural')], default='office', max_length=30)),
                ('max_participants', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)])),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('enable_recording', models.BooleanField(default=False)),
                ('room_code', models.CharField(default=vr_meet.models.unique_room_code, max_length=20, unique=True)),
                ('meet_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_meetings', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Room',
                'verbose_name_plural': 'Meeting Rooms',
                'db_table': 'meeting_rooms',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_code'], name='meeting_roo_room_co_a5fb8d_idx'), models.Index(fields=['status'], name='meeting_roo_status_10b149_idx'), models.Index(fields=['creator'], name='meeting_roo_creator_27fe11_idx')],
            },
        ),
    ]
