# Generated by Django 5.2.6 on 2025-11-19 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_meet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='candidate',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='candidate_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
