# Generated by Django 5.2.6 on 2025-11-20 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_meet', '0002_remove_meetingroom_candidate_meetingroom_candidates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meetingroom',
            name='meeting_roo_creator_27fe11_idx',
        ),
        migrations.RenameField(
            model_name='meetingroom',
            old_name='room_name',
            new_name='meeting_title',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_meeting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employer_meeting', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='host_email',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='purpose',
            field=models.CharField(choices=[('interview', 'Interview'), ('casual_call', 'Casual Call'), ('discussion', 'Discussion')], default='interview', max_length=30),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['employer'], name='meeting_roo_employe_d3ae66_idx'),
        ),
    ]
