# Generated by Django 5.2.8 on 2026-03-02 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_job_search_query'),
        ('projects', '0011_alter_project_search_query'),
        ('vr_meet', '0002_usergoogletoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The job this meeting is associated with (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this meeting is associated with (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title / position name.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Additional details about the offer.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual or fixed salary amount.', max_digits=12, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate (if applicable).', max_digits=10, null=True)),
                ('is_hourly', models.BooleanField(default=False, help_text='True if compensation is hourly-based, False for salary-based.')),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('date_of_joining', models.DateField(blank=True, help_text='Expected date of joining.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(help_text='The candidate receiving this offer.', on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(help_text='The employer who created this offer.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='The meeting this offer originated from.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vr_meet.meetingroom')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='offers_status_5a0bfa_idx'), models.Index(fields=['employer', 'status'], name='offers_employe_887182_idx'), models.Index(fields=['candidate', 'status'], name='offers_candida_5ab821_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'meeting'), name='unique_candidate_meeting_offer')],
            },
        ),
    ]
