# Generated by Django 5.2.8 on 2026-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_meet', '0004_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
