# Generated by Django 5.2.8 on 2026-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_meet', '0005_offer_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
