# Generated by Django 5.2.8 on 2026-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_meet', '0006_meetingroom_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_read_by_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_read_by_employer',
            field=models.BooleanField(default=False),
        ),
    ]
