# Generated by Django 5.2.8 on 2025-12-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
