# Generated by Django 5.2.8 on 2025-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_unread_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='unread_count',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, help_text='Number of unread messages'),
        ),
    ]
