# Generated by Django 5.2.6 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='total_candidates',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total unique candidates who messaged this employer'),
        ),
    ]
