# Generated by Django 5.2.6 on 2025-12-15 10:53

from django.db import migrations, models


def set_default_total_candidates(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    # Update all existing records to have total_candidates=0
    ChatMessage.objects.all().update(total_candidates=0)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_total_candidates'),
    ]

    operations = [
        migrations.RunPython(set_default_total_candidates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chatmessage',
            name='total_candidates',
            field=models.PositiveIntegerField(default=0, help_text='Total unique candidates who messaged this employer'),
        ),
    ]
