# Generated by Django 5.2.6 on 2025-12-15 10:55

from django.db import migrations
from django.apps import apps as django_apps

def update_total_candidates(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    User = apps.get_model('accounts', 'User')  # Adjust 'accounts' to your actual user app name
    
    if not User or not hasattr(User, 'user_type'):
        # If User model doesn't have user_type, we'll just set all to 1 as a fallback
        ChatMessage.objects.all().update(total_candidates=1)
        return
    
    # First, set all to 0 to avoid nulls
    ChatMessage.objects.all().update(total_candidates=0)
    
    # Get all employer recipients who have received messages
    from django.db.models import Count
    
    # Get all unique employer recipients with message counts
    employer_messages = ChatMessage.objects.filter(
        recipient__user_type='employer',
        sender__user_type='candidate'
    ).values('recipient').annotate(
        unique_candidates=Count('sender', distinct=True)
    )
    
    # Update each employer's messages with their unique candidate count
    for item in employer_messages:
        ChatMessage.objects.filter(
            recipient_id=item['recipient']
        ).update(total_candidates=item['unique_candidates'])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_make_total_candidates_nullable'),
    ]

    operations = [
        migrations.RunPython(update_total_candidates, migrations.RunPython.noop),
    ]
