# Generated by Django 5.2.8 on 2025-11-24 12:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import stories.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0002_add_query_field'),
        ('projects', '0002_add_query_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=stories.models.story_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='companies.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='jobs.job')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='projects.project')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_targets', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('company_id__isnull', False)), fields=('user', 'company_id'), name='unique_user_company_like'), models.UniqueConstraint(condition=models.Q(('project_id__isnull', False)), fields=('user', 'project_id'), name='unique_user_project_like'), models.UniqueConstraint(condition=models.Q(('job_id__isnull', False)), fields=('user', 'job_id'), name='unique_user_job_like')],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('job', 'Job')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Item',
                'verbose_name_plural': 'Saved Items',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('company_id__isnull', False)), fields=('user', 'company_id'), name='unique_user_company_save'), models.UniqueConstraint(condition=models.Q(('project_id__isnull', False)), fields=('user', 'project_id'), name='unique_user_project_save'), models.UniqueConstraint(condition=models.Q(('job_id__isnull', False)), fields=('user', 'job_id'), name='unique_user_job_save')],
            },
        ),
    ]
