# Generated by Django 5.2.8 on 2025-11-25 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='candidate_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='candidate_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='candidate_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='item_type',
            field=models.CharField(choices=[('company', 'Company'), ('project', 'Project'), ('job', 'Job'), ('candidate', 'Candidate')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_id__isnull', False)), fields=('user', 'candidate_id'), name='unique_user_candidate_like'),
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_id__isnull', False)), fields=('user', 'candidate_id'), name='unique_user_candidate_save'),
        ),
    ]
