# Generated by Django 5.2.8 on 2025-11-27 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_add_query_field'),
        ('stories', '0002_comment_candidate_id_like_candidate_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='job',
        ),
        migrations.RemoveField(
            model_name='story',
            name='project',
        ),
        migrations.RemoveField(
            model_name='story',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='story',
            name='target_object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to='stories.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='story',
            name='comments',
            field=models.ManyToManyField(related_name='commented_stories', through='stories.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='user_type',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('employer', 'Employer')], help_text='Type of user who created the story', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_story_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Story',
                'verbose_name_plural': 'Saved Stories',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'story')},
            },
        ),
        migrations.AddField(
            model_name='story',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_stories', through='stories.SavedStory', to=settings.AUTH_USER_MODEL),
        ),
    ]
