# Generated by Django 5.2.8 on 2025-11-27 11:43

import django.core.validators
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_comment_candidate_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.RemoveField(
            model_name='story',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.AddField(
            model_name='story',
            name='image_content',
            field=models.ImageField(blank=True, help_text='Image content for image stories', null=True, upload_to=stories.models.story_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='story',
            name='text_content',
            field=models.TextField(blank=True, help_text='Text content for text stories', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='video_content',
            field=models.FileField(blank=True, help_text='Video content for video stories', null=True, upload_to=stories.models.story_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
    ]
