# Generated by Django 5.2.8 on 2025-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_remove_story_content_remove_story_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='user_type',
            field=models.CharField(default='candidate', editable=False, help_text="Automatically set to 'employer' or 'candidate' based on user's profile", max_length=10),
        ),
    ]
