# Generated by Django 5.2.8 on 2025-11-28 12:09

from django.db import migrations

def link_stories_to_projects_and_jobs(apps, schema_editor):
    Story = apps.get_model('stories', 'Story')
    Project = apps.get_model('projects', 'Project')
    Job = apps.get_model('jobs', 'Job')
    
    # Link project stories
    for story in Story.objects.filter(text_content__startswith='Project: '):
        if not story.project_id and story.company:
            # Extract project title from text_content (remove 'Project: ' prefix)
            project_title = story.text_content[9:].strip()
            try:
                # Find project by title and company
                project = Project.objects.filter(
                    title=project_title,
                    company=story.company
                ).first()
                if project:
                    story.project = project
                    story.save(update_fields=['project'])
            except Exception as e:
                print(f"Error linking story {story.id} to project: {e}")
    
    # Link job stories
    for story in Story.objects.filter(text_content__startswith='Job: '):
        if not story.job_id and story.company:
            # Extract job title from text_content (remove 'Job: ' prefix)
            job_title = story.text_content[5:].strip()
            try:
                # Find job by title and company
                job = Job.objects.filter(
                    title=job_title,
                    company=story.company
                ).first()
                if job:
                    story.job = job
                    story.save(update_fields=['job'])
            except Exception as e:
                print(f"Error linking story {story.id} to job: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_add_project_and_job_to_story'),
        ('projects', '0001_initial'),  # Add this if not already present
        ('jobs', '0001_initial'),      # Add this if not already present
    ]

    operations = [
        migrations.RunPython(link_stories_to_projects_and_jobs, migrations.RunPython.noop),
    ]
