# Generated by Django 5.2.8 on 2025-12-01 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_options'),
        ('stories', '0007_link_existing_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='candidates.candidate'),
        ),
    ]
