# Generated by Django 5.2.8 on 2026-01-06 05:52

import django.core.validators
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_comment_company_comment_job_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image_content',
            field=models.ImageField(blank=True, help_text='Image content for image stories', null=True, upload_to=stories.models.story_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg', 'ico', 'tiff', 'tif', 'heic', 'heif'])]),
        ),
    ]
