# Generated by Django 5.2.8 on 2026-02-17 06:48

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_timezone',
            field=timezone_field.fields.TimeZoneField(db_column='timezone', default='America/New_York', help_text="User's preferred timezone"),
        ),
    ]
