# Generated by Django 5.2.6 on 2025-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordreset'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordreset',
            name='password_re_token_fb23e2_idx',
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='token',
            new_name='reset_token',
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['reset_token'], name='password_re_reset_t_cd82bb_idx'),
        ),
    ]
