# Generated by Django 5.2.6 on 2025-09-29 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_passwordreset_password_re_token_fb23e2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='otp',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'OTP must be a 6-digit numeric code')]),
        ),
    ]
