# Generated by Django 5.2.6 on 2025-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordreset_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='reset_token',
            field=models.TextField(db_index=True),
        ),
    ]
