# Generated by Django 5.2.6 on 2025-10-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_passwordreset_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='otp',
        ),
    ]
