# Generated by Django 5.2.8 on 2025-11-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_add_query_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
    ]
