# Generated by Django 5.2.8 on 2025-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_data',
            field=models.JSONField(blank=True, help_text='Stores parsed CV/Resume data', null=True),
        ),
    ]
