# Generated by Django 5.2.6 on 2025-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_remove_candidate_resume_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="seniority",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("junior", "Junior"),
                    ("intermediate", "Intermediate"),
                    ("mid-level", "Mid Level"),
                    ("senior", "Senior"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
    ]
