# Generated by Django 5.2.8 on 2025-12-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_resume_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
