# Generated by Django 5.2.8 on 2025-12-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_resume_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='query',
            new_name='search_query',
        ),
    ]
