# Generated by Django 5.2.6 on 2025-10-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0007_workdna_extra_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="candidate",
            name="viewers",
            field=models.JSONField(default=list),
        ),
    ]
