# Generated by Django 5.2.8 on 2025-12-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_fix_duplicate_query_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='query',
        ),
    ]
