# Generated by Django 5.2.6 on 2025-12-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_fix_resume_data_column'),
        ('candidates', '0008_remove_candidate_query'),
    ]

    operations = [
    ]
