# Generated by Django 5.2.6 on 2025-10-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidate_profile_views_candidate_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='candidates/profile_images/'),
        ),
    ]
