# Generated by Django 5.2.8 on 2025-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_merge_20251209_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to='candidates/resumes/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video_intro_url',
            field=models.FileField(blank=True, null=True, upload_to='candidates/videos/'),
        ),
    ]
