# Generated by Django 4.2.7 on 2025-03-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_referencerequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequest',
            name='reply_message',
            field=models.TextField(blank=True, null=True, verbose_name='Reference Response'),
        ),
    ]
