# Generated by Django 5.2.8 on 2025-12-23 06:04

import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_workdnaquestion_evaluation_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_validators.image_upload_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_validators.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video_intro_url',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_validators.video_upload_path),
        ),
    ]
