# Generated by Django 5.2.6 on 2025-10-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_add_reply_message_to_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencerequest',
            name='reply_message',
        ),
    ]
