# Generated by Django 5.2.8 on 2025-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_alter_candidate_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
