# Generated by Django 5.2.6 on 2025-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_add_reply_message_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequest',
            name='reply_message',
            field=models.TextField(blank=True, null=True, verbose_name='Reference Response'),
        ),
    ]
