# Generated by Django 5.2.8 on 2026-01-06 05:52

import django.core.validators
import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_alter_candidate_resume_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_validators.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg', 'ico', 'tiff', 'tif', 'heic', 'heif'])]),
        ),
    ]
