# Generated by Django 5.2.6 on 2025-11-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_add_reply_message_field_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_index_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_tags',
            field=models.JSONField(default=list),
        ),
    ]
