# Generated by Django 5.2.8 on 2026-01-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_candidate_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
