# Generated by Django 5.2.6 on 2025-11-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_alter_candidate_candidate_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDNAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('questions', models.JSONField()),
                ('total_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_dna_questions', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Work DNA Question',
                'verbose_name_plural': 'Work DNA Questions',
                'db_table': 'candidate_work_dna_questions',
            },
        ),
    ]
