# Generated by Django 5.2.8 on 2026-01-20 12:05

from django.db import migrations
import json


def clean_intro_video_description_data(apps, schema_editor):
    """
    Clean existing intro_video_description data to ensure it's valid JSON
    """
    Candidate = apps.get_model('candidates', 'Candidate')
    
    for candidate in Candidate.objects.all():
        if candidate.intro_video_description:
            # If it's already a string, try to parse it as JSON
            if isinstance(candidate.intro_video_description, str):
                try:
                    # Try to parse as JSON
                    json.loads(candidate.intro_video_description)
                    # If successful, keep as is (Django will handle conversion)
                except (json.JSONDecodeError, ValueError):
                    # If not valid JSON, set to empty dict
                    candidate.intro_video_description = {}
                    candidate.save(update_fields=['intro_video_description'])
            # If it's None or empty, set to empty dict
            elif candidate.intro_video_description is None:
                candidate.intro_video_description = {}
                candidate.save(update_fields=['intro_video_description'])


def reverse_clean_intro_video_description_data(apps, schema_editor):
    """
    Reverse the data cleaning (set all to None)
    """
    Candidate = apps.get_model('candidates', 'Candidate')
    Candidate.objects.all().update(intro_video_description=None)


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_professional_title'),
    ]

    operations = [
        migrations.RunPython(
            clean_intro_video_description_data,
            reverse_clean_intro_video_description_data,
        ),
    ]
