# Generated by Django 5.2.8 on 2026-01-20 12:10

from django.db import migrations


def fix_intro_video_description_json(apps, schema_editor):
    """
    Fix intro_video_description field by setting all values to empty dict
    """
    with schema_editor.connection.cursor() as cursor:
        # Set all records to empty dict
        cursor.execute("""
            UPDATE candidates 
            SET intro_video_description = '{}'::jsonb
        """)


def reverse_fix_intro_video_description_json(apps, schema_editor):
    """
    Reverse the fix (set all back to NULL)
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE candidates 
            SET intro_video_description = NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_clean_intro_video_description_data'),
    ]

    operations = [
        migrations.RunPython(
            fix_intro_video_description_json,
            reverse_fix_intro_video_description_json,
        ),
    ]
