# Generated by Django 5.2.8 on 2026-01-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_fix_intro_video_description_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='intro_video_description',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
