# Generated by Django 5.2.6 on 2025-11-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_workdnaquestion_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdna',
            name='candidate',
        ),
        migrations.AlterUniqueTogether(
            name='workdnaanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workdnaanswer',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='WorkDNA',
        ),
        migrations.DeleteModel(
            name='WorkDNAAnswer',
        ),
    ]
