# Generated by Django 5.2.8 on 2026-01-23 10:23

import django.core.validators
import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_alter_intro_video_description_to_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_validators.achievement_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg', 'ico', 'tiff', 'tif', 'heic', 'heif'])]),
        ),
    ]
