# Generated by Django 5.2.8 on 2026-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], help_text='For Grade system (A-F)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='grading_system',
            field=models.CharField(blank=True, choices=[('gpa', 'GPA'), ('gpr', 'GPR'), ('grade', 'Grade'), ('marks', 'Marks')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='obtained_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For Marks system', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For Marks system', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For GPA/GPR system', max_digits=3, null=True),
        ),
    ]
