# Generated by Django 5.2.8 on 2026-01-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_candidate_ai_resume_url'),
        ('candidates', '0021_education_grade_education_grading_system_and_more'),
    ]

    operations = [
    ]
