# Generated by Django 5.2.8 on 2026-02-02 09:53

import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_merge_20260129_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ai_resume_url',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_validators.resume_upload_path),
        ),
    ]
