# Generated by Django 5.2.8 on 2026-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0026_alter_candidate_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequest',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the reference email was successfully sent.', null=True),
        ),
        migrations.AddField(
            model_name='referencerequest',
            name='grace_period_applied',
            field=models.BooleanField(default=False, help_text='Whether the 7-day grace period has already been applied.'),
        ),
        migrations.AlterField(
            model_name='referencerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
