# Generated by Django 5.2.8 on 2026-03-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0027_referencerequest_email_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencerequest',
            name='grace_period_applied',
        ),
    ]
