# Generated by Django 5.2.8 on 2026-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0028_remove_referencerequest_grace_period_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequest',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
