# Generated by Django 5.2.8 on 2026-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0029_referencerequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='banner_seen',
            field=models.BooleanField(default=False),
        ),
    ]
