# Generated by Django 5.2.8 on 2026-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0032_referencerequest_request_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequest',
            name='response_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
