# Generated by Django 5.2.8 on 2026-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0033_referencerequest_response_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='public_share_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
