"""
Django settings for flit_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)


ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',')])
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

THIRD_PARTY_APPS = [
    'rest_framework',
    'corsheaders',
    'django_filters',
    'storages',
    'timezone_field',
]


LOCAL_APPS = [
    'accounts',
    'candidates',
    'employers',
    'companies',
    'jobs',
    'projects',
    'applications',   
    'chat',
    'vr_meet',
    'stories',
]

# Add 'channels' to the beginning of INSTALLED_APPS
INSTALLED_APPS = ['channels'] + DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ASGI Application
ASGI_APPLICATION = 'flit_backend.asgi.application'

# Redis & Channel Layer Configuration
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')

# ponytail: in-memory layer for single-process local dev (no Redis to install);
# set USE_REDIS_CHANNEL_LAYER=True once you run more than one worker.
if config('USE_REDIS_CHANNEL_LAYER', default=not DEBUG, cast=bool):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }

# A cross-worker cache is opt-in via CACHE_URL, so local dev needs no Redis.
# Set it in production (e.g. CACHE_URL=$REDIS_URL) so the background upload status
# written by one worker is readable by the worker serving
# /candidates/processing-status/. Without it Django's per-process default is used,
# which reports reliably only from a single-worker deployment.
# NOTE: this cache also backs DRF login throttling — an unreachable cache 500s login.
CACHE_URL = config('CACHE_URL', default='')
if CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CACHE_URL,
        },
    }




MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'flit_backend.middleware.APILoggingMiddleware',
]

ROOT_URLCONF = 'flit_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', cast=bool)
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', cast=bool)


# ASGI application for Django Channels
ASGI_APPLICATION = 'flit_backend.asgi.application'

# WSGI application for traditional WSGI
WSGI_APPLICATION = 'flit_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# User Role Constants
USER_ROLE_CANDIDATE = 'candidate'
USER_ROLE_EMPLOYER = 'employer'
USER_ROLE_ADMIN = 'admin'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'accounts.validators.MaximumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# # Media files
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.CustomPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'login': '10/min',
    },
}

# File upload limits — sized for the company gallery flow (up to 15 images, ~10 MB each).
# Upstream proxy (Nginx/ALB) request body limit must be >= DATA_UPLOAD_MAX_MEMORY_SIZE.
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FILES = 25


# Explicitly trust local frontend origins for CSRF origin checking
# Email settings (force SMTP even in DEBUG)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend password reset URL (used in reset emails)
PASSWORD_RESET_URL = config('PASSWORD_RESET_URL')

# JWT Token Expiry Time
JWT_ACCESS_TOKEN_EXPIRY_HOURS = 8
JWT_REFRESH_TOKEN_EXPIRY_DAYS = 7

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=JWT_ACCESS_TOKEN_EXPIRY_HOURS * 60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=JWT_REFRESH_TOKEN_EXPIRY_DAYS),

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# AWS S3 Configuration

AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = config("S3_BUCKET_NAME")
AWS_S3_REGION_NAME = config("AWS_REGION")
AWS_S3_SIGNATURE_NAME = 's3v4'
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

AWS_S3_FILE_OVERWRITE = True
AWS_DEFAULT_ACL = None
AWS_IS_GZIPPED = False
AWS_S3_VERIFY = True
AWS_S3_SECURE_URLS = True

STORAGES = {
    "default": {  
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "LOCATION": "media",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
        "LOCATION": "staticfiles",
    }
}

# Google Configuration
CLIENT_ID = config('GOOGLE_CLIENT_ID')
CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')
REDIRECT_URI = config('GOOGLE_REDIRECT_URI')
AUTH_URI = config('AUTH_URI')
TOKEN_URI = config('TOKEN_URI')
GOOGLE_SCOPES = config('GOOGLE_SCOPES')

# Social sign-in (distinct from the VR-Meet Google Calendar OAuth above).
# Empty defaults keep boot working; unconfigured providers 400 with provider_not_configured.
SOCIAL_OAUTH = {
    p: {
        'client_id': config(f'SOCIAL_{p.upper()}_CLIENT_ID', default=''),
        'client_secret': config(f'SOCIAL_{p.upper()}_CLIENT_SECRET', default=''),
    }
    for p in ('google', 'microsoft', 'github', 'linkedin')
}

# Logging Configuration
# Logging Configuration
import os

# Ensure logs directory exists
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',  
        },
        'api_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'API_access.log'),
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'security_warnings.log'),
            'formatter': 'verbose',
        },
        'exceptions_file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'exceptions.log'),
            'formatter': 'verbose',
        },
        'debug_file': {  
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
      
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'api_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },

     
        'chat.consumers': {
            'handlers': ['console', 'debug_file'],
            'level': 'DEBUG', 
            'propagate': False,
        },
        'chat': {  
            'handlers': ['console', 'debug_file'],
            'level': 'DEBUG',
            'propagate': False,
        },

      
        'daphne': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'asyncio': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'debug_file'],
        'level': 'INFO',
    },
}

# AI Related Variables

# ponytail: strip trailing slash once here -- every f"{FLIT_AI_URL}/path" call site
# otherwise builds a double slash, which the ML API 404s on.
FLIT_AI_URL=config('FLIT_AI_URL').rstrip('/')


# Reference Request Variable
FLIT_REQUEST_URL = config('FLIT_REQUEST_URL')

