# Generated by Django 5.2.6 on 2025-10-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_name_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_zip_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='company',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='company',
            name='perks',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work_life_balance',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work_style',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000')], max_length=30),
        ),
    ]
