# Generated by Django 5.2.8 on 2026-02-02 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.TextField(blank=True, help_text='List key benefits and perks'),
        ),
        migrations.AddField(
            model_name='company',
            name='culture',
            field=models.TextField(blank=True, help_text='Describe the company culture'),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="{'linkedin': 'url', 'twitter': 'url', ...}"),
        ),
        migrations.AddField(
            model_name='company',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('mixed', 'Mixed'), ('flexible', 'Flexible')], default='onsite', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companies/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Image',
                'verbose_name_plural': 'Company Images',
                'db_table': 'company_images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Milestone',
                'verbose_name_plural': 'Company Milestones',
                'db_table': 'company_milestones',
                'ordering': ['-year'],
            },
        ),
    ]
