# Generated by Django 5.2.6 on 2025-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_name_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
