# Generated by Django 5.2.8 on 2026-02-02 09:53

import django.core.validators
import utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_benefits_company_culture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_validators.company_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'svg', 'ico', 'tiff', 'tif', 'heic', 'heif'])]),
        ),
        migrations.AlterField(
            model_name='company',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.ImageField(upload_to=utils.file_validators.company_gallery_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
