# Generated by Django 5.2.8 on 2026-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_logo_alter_company_work_mode_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE companies DROP CONSTRAINT IF EXISTS companies_founded_year_check;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="ALTER TABLE companies ALTER COLUMN founded_year TYPE date USING (CASE WHEN founded_year IS NOT NULL THEN (founded_year::text || '-01-01')::date ELSE NULL END);",
            reverse_sql="ALTER TABLE companies ALTER COLUMN founded_year TYPE integer USING extract(year from founded_year)::integer;"
        ),
        migrations.AlterField(
            model_name='company',
            name='founded_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE company_milestones DROP CONSTRAINT IF EXISTS company_milestones_year_check;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="ALTER TABLE company_milestones ALTER COLUMN year TYPE date USING (year::text || '-01-01')::date;",
            reverse_sql="ALTER TABLE company_milestones ALTER COLUMN year TYPE integer USING extract(year from year)::integer;"
        ),
        migrations.AlterField(
            model_name='companymilestone',
            name='year',
            field=models.DateField(),
        ),
    ]
