# Generated by Django 5.2.6 on 2025-10-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_is_completed"),
        ("companies", "0004_alter_company_description_alter_company_location"),
    ]

    operations = []
