# Generated by Django 5.2.6 on 2025-10-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_merge_20251008_1145'),
        ('companies', '0005_merge_20251008_1550'),
    ]

    operations = [
    ]
