"""
Central currency choices for use across all models (Job, Project, Candidate).
"""

CURRENCY_CHOICES = [
    ('USD', 'USD ($) - US Dollar'),
    ('EUR', 'EUR (€) - Euro'),
    ('GBP', 'GBP (£) - British Pound'),
    ('CAD', 'CAD (C$) - Canadian Dollar'),
    ('AUD', 'AUD (A$) - Australian Dollar'),
    ('JPY', 'JPY (¥) - Japanese Yen'),
    ('CNY', 'CNY (¥) - Chinese Yuan'),
    ('INR', 'INR (₹) - Indian Rupee'),
    ('PKR', 'PKR (₨) - Pakistani Rupee'),
    ('BRL', 'BRL (R$) - Brazilian Real'),
    ('MXN', 'MXN ($) - Mexican Peso'),
    ('CHF', 'CHF (Fr) - Swiss Franc'),
    ('SEK', 'SEK (kr) - Swedish Krona'),
    ('NOK', 'NOK (kr) - Norwegian Krone'),
    ('DKK', 'DKK (kr) - Danish Krone'),
    ('NZD', 'NZD (NZ$) - New Zealand Dollar'),
    ('SGD', 'SGD (S$) - Singapore Dollar'),
    ('HKD', 'HKD (HK$) - Hong Kong Dollar'),
    ('KRW', 'KRW (₩) - South Korean Won'),
    ('TRY', 'TRY (₺) - Turkish Lira'),
    ('RUB', 'RUB (₽) - Russian Ruble'),
    ('ZAR', 'ZAR (R) - South African Rand'),
    ('AED', 'AED (د.إ) - UAE Dirham'),
    ('SAR', 'SAR (﷼) - Saudi Riyal'),
    ('PLN', 'PLN (zł) - Polish Zloty'),
    ('THB', 'THB (฿) - Thai Baht'),
    ('IDR', 'IDR (Rp) - Indonesian Rupiah'),
    ('MYR', 'MYR (RM) - Malaysian Ringgit'),
    ('PHP', 'PHP (₱) - Philippine Peso'),
    ('VND', 'VND (₫) - Vietnamese Dong'),
    ('EGP', 'EGP (£) - Egyptian Pound'),
    ('NGN', 'NGN (₦) - Nigerian Naira'),
    ('KES', 'KES (KSh) - Kenyan Shilling'),
    ('BDT', 'BDT (৳) - Bangladeshi Taka'),
    ('COP', 'COP ($) - Colombian Peso'),
    ('ARS', 'ARS ($) - Argentine Peso'),
    ('CLP', 'CLP ($) - Chilean Peso'),
    ('PEN', 'PEN (S/) - Peruvian Sol'),
    ('ILS', 'ILS (₪) - Israeli Shekel'),
    ('CZK', 'CZK (Kč) - Czech Koruna'),
    ('HUF', 'HUF (Ft) - Hungarian Forint'),
    ('RON', 'RON (lei) - Romanian Leu'),
    ('BGN', 'BGN (лв) - Bulgarian Lev'),
    ('HRK', 'HRK (kn) - Croatian Kuna'),
    ('TWD', 'TWD (NT$) - Taiwan Dollar'),
    ('QAR', 'QAR (﷼) - Qatari Riyal'),
    ('KWD', 'KWD (د.ك) - Kuwaiti Dinar'),
    ('BHD', 'BHD (BD) - Bahraini Dinar'),
    ('OMR', 'OMR (﷼) - Omani Rial'),
    ('LKR', 'LKR (Rs) - Sri Lankan Rupee'),
]

# Symbol mapping for quick lookup
CURRENCY_SYMBOLS = {
    'USD': '$', 'EUR': '€', 'GBP': '£', 'CAD': 'C$', 'AUD': 'A$',
    'JPY': '¥', 'CNY': '¥', 'INR': '₹', 'PKR': '₨', 'BRL': 'R$',
    'MXN': '$', 'CHF': 'Fr', 'SEK': 'kr', 'NOK': 'kr', 'DKK': 'kr',
    'NZD': 'NZ$', 'SGD': 'S$', 'HKD': 'HK$', 'KRW': '₩', 'TRY': '₺',
    'RUB': '₽', 'ZAR': 'R', 'AED': 'د.إ', 'SAR': '﷼', 'PLN': 'zł',
    'THB': '฿', 'IDR': 'Rp', 'MYR': 'RM', 'PHP': '₱', 'VND': '₫',
    'EGP': '£', 'NGN': '₦', 'KES': 'KSh', 'BDT': '৳', 'COP': '$',
    'ARS': '$', 'CLP': '$', 'PEN': 'S/', 'ILS': '₪', 'CZK': 'Kč',
    'HUF': 'Ft', 'RON': 'lei', 'BGN': 'лв', 'HRK': 'kn', 'TWD': 'NT$',
    'QAR': '﷼', 'KWD': 'د.ك', 'BHD': 'BD', 'OMR': '﷼', 'LKR': 'Rs',
}
