# Generated by Django 5.2.6 on 2025-10-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidate_resume_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="resume_file",
        ),
    ]
