# Generated by Django 5.2.6 on 2025-10-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0005_remove_candidate_seniority"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="video_transcription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
