# Generated by Django 5.2.6 on 2025-10-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_candidate_video_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="workdna",
            name="extra_answers",
            field=models.JSONField(default=dict),
        ),
    ]
