# Generated by Django 5.2.6 on 2025-10-29 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidate_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerequest',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
