# Generated by Django 5.2.6 on 2025-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_candidate_candidate_index_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_profile_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
