# Generated by Django 5.2.6 on 2025-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_candidate_profile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
