# Generated by Django 5.2.6 on 2025-11-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_workdnaquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDNAAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('selected_option', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_dna_answers', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Work DNA Answer',
                'verbose_name_plural': 'Work DNA Answers',
                'db_table': 'candidate_work_dna_answers',
                'unique_together': {('candidate', 'question_id')},
            },
        ),
    ]
