# Generated by Django 5.2.6 on 2025-11-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_workdnaanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdnaquestion',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
