# Generated by Django 5.2.6 on 2025-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_remove_workdna_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('mid-level', 'Mid-level'), ('senior-level', 'Senior-level')], max_length=20, null=True),
        ),
    ]
