# Generated by Django 5.2.6 on 2025-11-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidate_seniority_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_index_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='seniority_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20, null=True),
        ),
    ]
