# Generated by Django 5.2.6 on 2025-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_remove_candidate_candidate_index_id_candidate_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
